### ISSUE TITLE
Could not select Container Registry Namespace in Toolchain Wizard

### ISSUE THREAD

**Issue by rmey** [IBM-Cloud/jpetstore-kubernetes#11]
Hello,
I'm unable to select a registry namespace, I tried in all regions when running the Wizard in Cloud portal, which blocks the creation of the Toolchain. See screenshot.
[https://pasteboard.co/HXjfWwW.png](https://pasteboard.co/HXjfWwW.png)

**Comment by l2fprod** [comment]
something had changed in how toolchain handles the registry name and its region. updated wizard should fix this
